In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
countries = gpd.read_file('map.geo.json')
countries.sort_values('admin')

,featurecla,scalerank,labelrank,sovereignt,sov_a3,adm0_dif,level,type,tlc,admin,...,fclass_id,fclass_pl,fclass_gr,fclass_it,fclass_nl,fclass_se,fclass_bd,fclass_ua,filename,geometry
80,Admin-0 country,0,3,Afghanistan,AFG,0,2,Sovereign country,1,Afghanistan,...,None,None,None,None,None,None,None,None,AFG.geojson,"POLYGON ((74.54235 37.02167, 74.54742 37.01567..."
90,Admin-0 country,3,3,United Kingdom,GB1,1,2,Dependency,1,Akrotiri Sovereign Base Area,...,None,Admin-0 dependency,Admin-0 dependency,Admin-0 dependency,Admin-0 dependency,Admin-0 dependency,None,Admin-0 dependency,akrotiri.geojson,"POLYGON ((33.01563 34.63442, 33.00994 34.62490..."
220,Admin-0 country,3,6,Finland,FI1,1,2,Country,1,Aland,...,None,None,None,None,None,None,None,None,ALA.geojson,"MULTIPOLYGON (((20.27760 60.14216, 20.29762 60..."
186,Admin-0 country,0,6,Albania,ALB,0,2,Sovereign country,1,Albania,...,None,None,None,None,None,None,None,None,ALB.geojson,"POLYGON ((20.56715 41.87318, 20.54172 41.86158..."
148,Admin-0 country,0,3,Algeria,DZA,0,2,Sovereign country,1,Algeria,...,None,None,None,None,None,None,None,None,DZA.geojson,"POLYGON ((-4.82161 24.99506, -4.99519 25.10209..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Admin-0 country,0,7,Western Sahara,SAH,0,2,Indeterminate,1,Western Sahara,...,Unrecognized,Unrecognized,None,None,Unrecognized,None,None,None,ESH.geojson,"POLYGON ((-8.81703 27.66146, -8.81654 27.66147..."
84,Admin-0 country,0,3,Yemen,YEM,0,2,Sovereign country,1,Yemen,...,None,None,None,None,None,None,None,None,YEM.geojson,"MULTIPOLYGON (((51.97861 18.99564, 51.98569 18..."
131,Admin-0 country,0,3,Zambia,ZMB,0,2,Sovereign country,1,Zambia,...,None,None,None,None,None,None,None,None,ZMB.geojson,"POLYGON ((32.92086 -9.40790, 32.92303 -9.46629..."
146,Admin-0 country,0,3,Zimbabwe,ZWE,0,2,Sovereign country,1,Zimbabwe,...,None,None,None,None,None,None,None,None,ZWE.geojson,"POLYGON ((25.25978 -17.79411, 25.26671 -17.800..."
150,Admin-0 country,0,4,eSwatini,SWZ,0,2,Sovereign country,1,eSwatini,...,None,None,None,None,None,None,None,None,SWZ.geojson,"POLYGON ((31.94924 -25.95810, 31.97529 -25.980..."

In [3]:
csv_file_path = 'API_SP.POP.TOTL_DS2_en_csv_v2_85.csv'
population_df = pd.read_csv(csv_file_path, skiprows=4, header=0)
population_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Unnamed: 67
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720859132.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1786038.0,1761985.0,NaN
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5542459.0,5646668.0,5753386.0,5860197.0,5973803.0,6097298.0,...,27753304.0,28516545.0,29274002.0,30034389.0,30790513.0,31546691.0,32284046.0,32981641.0,33696614.0,NaN
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16520441.0,16989464.0,17503133.0,18042215.0,18603097.0,19187194.0,...,54729551.0,55876504.0,56422274.0,56641209.0,57339635.0,58087055.0,58801927.0,59392255.0,59893885.0,NaN
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3119430.0,3219451.0,3323427.0,3431381.0,3542764.0,3658024.0,...,15737793.0,16248230.0,16767761.0,17298054.0,17835893.0,18380477.0,18927715.0,19473125.0,20017675.0,NaN
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3806310.0,3925952.0,4049778.0,4177931.0,4310332.0,4447149.0,...,13855753.0,14154937.0,14452704.0,14751101.0,15052184.0,15354608.0,15669666.0,15993524.0,16320537.0,NaN

In [4]:
corrections = {
    'Bahamas, The': 'The Bahamas',
    'Brunei Darussalam': 'Brunei',
    'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
    'Congo, Rep.': 'Republic of the Congo',
    "Cote d'Ivoire": 'Ivory Coast',
    'Curacao': 'Curaçao',
    'Egypt, Arab Rep.': 'Egypt',
    'Eswatini': 'eSwatini',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'Hong Kong S.A.R.',
    'Iran, Islamic Rep.': 'Iran',
    "Korea, Dem. People's Rep.": 'North Korea',
    'Korea, Rep.': 'South Korea',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Macao SAR, China': 'Macao S.A.R',
    'Russian Federation': 'Russia',
    'Sao Tome and Principe': 'São Tomé and Principe',
    'Serbia': 'Republic of Serbia',
    'Sint Maarten (Dutch part)': 'Sint Maarten',
    'Slovak Republic': 'Slovakia',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',
    'St. Lucia': 'Saint Lucia',
    'St. Martin (French part)': 'Saint Martin',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Syrian Arab Republic': 'Syria',
    'Tanzania': 'United Republic of Tanzania',
    'Timor-Leste': 'East Timor',
    'Turkiye': 'Turkey',
    'United States': 'United States of America',
    'Viet Nam': 'Vietnam',
    'Virgin Islands (U.S.)': 'United States Virgin Islands',
    'Yemen, Rep.': 'Yemen'
}

population_df['Country Name'] = population_df['Country Name'].replace(corrections)

In [5]:
countries_json = countries.sort_values('admin')['admin'].tolist()
len(countries_json)

258

In [6]:
countries_json

['Afghanistan',
 'Akrotiri Sovereign Base Area',
 'Aland',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antarctica',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Ashmore and Cartier Islands',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bajo Nuevo Bank (Petrel Is.)',
 'Bangladesh',
 'Barbados',
 'Baykonur Cosmodrome',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bir Tawil',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brazilian Island',
 'British Indian Ocean Territory',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Clipperton Island',
 'Colombia',
 'Comoros',
 'Cook Islands',
 'Coral Sea Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Cyprus No Mans Area',
 'Czechia',
 'Democratic Republic of the Congo',
 'Denmark',
 'Dhekelia Sovereign Base Area',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Federated States of Micronesia',
 'Fiji',
 'Finland',
 'France',
 'French Polynesia',
 'French Southern and Antarctic Lands',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heard Island and McDonald Islands',
 'Honduras',
 'Hong Kong S.A.R.',
 'Hungary',
 'Iceland',
 'India',
 'Indian Ocean Territories',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao S.A.R',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'North Korea',
 'North Macedonia',
 'Northern Cyprus',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn Islands',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Serbia',
 'Republic of the Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Barthelemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Scarborough Reef',
 'Senegal',
 'Serranilla Bank',
 'Seychelles',
 'Siachen Glacier',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Georgia and the Islands',
 'South Korea',
 'South Sudan',
 'Southern Patagonian Ice Field',
 'Spain',
 'Spratly Islands',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Principe',
 'Taiwan',
 'Tajikistan',
 'Thailand',
 'The Bahamas',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'US Naval Base Guantanamo Bay',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States Minor Outlying Islands',
 'United States Virgin Islands',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican',
 'Venezuela',
 'Vietnam',
 'Wallis and Futuna',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'eSwatini']

In [7]:
countries_csv = population_df.sort_values('Country Name')['Country Name'].tolist()
len(countries_csv)

266

In [8]:
countries_csv

['Afghanistan',
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Arab World',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Republic',
 'Central Europe and the Baltics',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czechia',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'Fragile and conflict affected situations',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'Honduras',
 'Hong Kong S.A.R.',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Lao PDR',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Macao S.A.R',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Fed. Sts.',
 'Middle East & North Africa',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle East & North Africa (excluding high income)',
 'Middle income',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North America',
 'North Korea',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'Not classified',
 'OECD members',
 'Oman',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico',
 'Qatar',
 'Republic of Serbia',
 'Republic of the Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Small states',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Principe',
 'Tajikistan',
 'Thailand',
 'The Bahamas',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States Virgin Islands',
 'United States of America',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela, RB',
 'Vietnam',
 'West Bank and Gaza',
 'World',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'eSwatini']

In [9]:
in_csv_and_json = []
for item in countries_json:
    if item in countries_csv:
        in_csv_and_json.append(item)

In [10]:
len(in_csv_and_json)

212

In [11]:
in_csv = []
for item in countries_csv:
    if item not in countries_json:
        in_csv.append(item)

In [12]:
len(in_csv)

54

In [13]:
in_csv

['Africa Eastern and Southern',
 'Africa Western and Central',
 'Arab World',
 'Caribbean small states',
 'Central Europe and the Baltics',
 'Channel Islands',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Fragile and conflict affected situations',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Lao PDR',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Least developed countries: UN classification',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Micronesia, Fed. Sts.',
 'Middle East & North Africa',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle East & North Africa (excluding high income)',
 'Middle income',
 'North America',
 'Not classified',
 'OECD members',
 'Other small states',
 'Pacific island small states',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Small states',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Upper middle income',
 'Venezuela, RB',
 'West Bank and Gaza',
 'World']

In [14]:
in_json = []
for item in countries_json:
    if item not in countries_csv:
        in_json.append(item)

In [15]:
len(in_json)

46

In [16]:
in_json

['Akrotiri Sovereign Base Area',
 'Aland',
 'Anguilla',
 'Antarctica',
 'Ashmore and Cartier Islands',
 'Bajo Nuevo Bank (Petrel Is.)',
 'Baykonur Cosmodrome',
 'Bir Tawil',
 'Brazilian Island',
 'British Indian Ocean Territory',
 'Clipperton Island',
 'Cook Islands',
 'Coral Sea Islands',
 'Cyprus No Mans Area',
 'Dhekelia Sovereign Base Area',
 'Falkland Islands',
 'Federated States of Micronesia',
 'French Southern and Antarctic Lands',
 'Guernsey',
 'Heard Island and McDonald Islands',
 'Indian Ocean Territories',
 'Jersey',
 'Laos',
 'Montserrat',
 'Niue',
 'Norfolk Island',
 'Northern Cyprus',
 'Palestine',
 'Pitcairn Islands',
 'Saint Barthelemy',
 'Saint Helena',
 'Saint Pierre and Miquelon',
 'Scarborough Reef',
 'Serranilla Bank',
 'Siachen Glacier',
 'Somaliland',
 'South Georgia and the Islands',
 'Southern Patagonian Ice Field',
 'Spratly Islands',
 'Taiwan',
 'US Naval Base Guantanamo Bay',
 'United States Minor Outlying Islands',
 'Vatican',
 'Venezuela',
 'Wallis and Futuna',
 'Western Sahara']

In [17]:
gdf_merged = countries.merge(population_df, left_on='admin', right_on='Country Name', how='left')
gdf_merged.head(10)

,featurecla,scalerank,labelrank,sovereignt,sov_a3,adm0_dif,level,type,tlc,admin,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Unnamed: 67
0,Admin-0 country,0,5,Costa Rica,CRI,0,2,Sovereign country,1,Costa Rica,...,4844288.0,4895242.0,4945205.0,4993842.0,5040734.0,5084532.0,5123105.0,5153957.0,5180829.0,NaN
1,Admin-0 country,0,5,Nicaragua,NIC,0,2,Sovereign country,1,Nicaragua,...,6208676.0,6298598.0,6389235.0,6480532.0,6572233.0,6663924.0,6755895.0,6850540.0,6948392.0,NaN
2,Admin-0 country,3,6,France,FR1,1,2,Dependency,1,Saint Martin,...,35261.0,35020.0,34811.0,34496.0,33852.0,33121.0,32553.0,31948.0,31791.0,NaN
3,Admin-0 country,3,6,Netherlands,NL1,1,2,Country,1,Sint Maarten,...,37685.0,38825.0,39969.0,40574.0,40895.0,41608.0,42310.0,42668.0,42848.0,NaN
4,Admin-0 country,0,5,Haiti,HTI,0,2,Sovereign country,1,Haiti,...,10412740.0,10563757.0,10713849.0,10863543.0,11012421.0,11160438.0,11306801.0,11447569.0,11584996.0,NaN
5,Admin-0 country,0,5,Dominican Republic,DOM,0,2,Sovereign country,1,Dominican Republic,...,10282115.0,10405832.0,10527592.0,10647244.0,10765531.0,10881882.0,10999664.0,11117873.0,11228821.0,NaN
6,Admin-0 country,0,6,El Salvador,SLV,0,2,Sovereign country,1,El Salvador,...,6209526.0,6231066.0,6250510.0,6266654.0,6276342.0,6280217.0,6292731.0,6314167.0,6336392.0,NaN
7,Admin-0 country,0,3,Guatemala,GTM,0,2,Sovereign country,1,Guatemala,...,15306316.0,15567419.0,15827690.0,16087418.0,16346950.0,16604026.0,16858333.0,17109746.0,17357886.0,NaN
8,Admin-0 country,0,10,Cuba,CU1,1,2,Lease,1,US Naval Base Guantanamo Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Admin-0 country,0,3,Cuba,CU1,1,1,Sovereignty,1,Cuba,...,11332026.0,11339894.0,11342012.0,11336405.0,11328244.0,11316697.0,11300698.0,11256372.0,11212191.0,NaN

In [18]:
years_of_interest = ['Country Name', '2022','2021','2020', '2019', '2018']  
population_df_selected = population_df[years_of_interest]

In [19]:
gdf_merged[['admin','2018','2019','2020','2021','2022']]

,admin,2018,2019,2020,2021,2022
0,Costa Rica,5040734.0,5084532.0,5123105.0,5153957.0,5180829.0
1,Nicaragua,6572233.0,6663924.0,6755895.0,6850540.0,6948392.0
2,Saint Martin,33852.0,33121.0,32553.0,31948.0,31791.0
3,Sint Maarten,40895.0,41608.0,42310.0,42668.0,42848.0
4,Haiti,11012421.0,11160438.0,11306801.0,11447569.0,11584996.0
...,...,...,...,...,...,...
253,Mauritius,1265577.0,1265985.0,1266014.0,1266334.0,1262523.0
254,British Indian Ocean Territory,NaN,NaN,NaN,NaN,NaN
255,Maldives,489758.0,504508.0,514438.0,521457.0,523787.0
256,South Georgia and the Islands,NaN,NaN,NaN,NaN,NaN
257,Clipperton Island,NaN,NaN,NaN,NaN,NaN

In [20]:
gdf_filtered = gdf_merged[pd.isna(gdf_merged['2018'])]

In [21]:
countries = ', '.join(gdf_filtered['admin'])

In [22]:
countries

'US Naval Base Guantanamo Bay, Saint Pierre and Miquelon, United States Minor Outlying Islands, Montserrat, Saint Barthelemy, Anguilla, Bajo Nuevo Bank (Petrel Is.), Serranilla Bank, Dhekelia Sovereign Base Area, Palestine, Laos, Northern Cyprus, Cyprus No Mans Area, Siachen Glacier, Baykonur Cosmodrome, Akrotiri Sovereign Base Area, Taiwan, Indian Ocean Territories, Spratly Islands, Scarborough Reef, Brazilian Island, Venezuela, Southern Patagonian Ice Field, Falkland Islands, Somaliland, Western Sahara, Bir Tawil, Vatican, Jersey, Guernsey, Aland, Pitcairn Islands, Norfolk Island, Cook Islands, Wallis and Futuna, Federated States of Micronesia, Niue, Coral Sea Islands, Ashmore and Cartier Islands, Antarctica, French Southern and Antarctic Lands, Heard Island and McDonald Islands, Saint Helena, British Indian Ocean Territory, South Georgia and the Islands, Clipperton Island'

In [23]:
gdf_merged = gdf_merged.rename(columns={'2022': 'population_2022',
                                              '2021': 'population_2021',
                                              '2020': 'population_2020',
                                              '2019': 'population_2019',
                                              '2018': 'population_2018'})

In [24]:
gdf_merged = gdf_merged.drop(columns=['Unnamed: 67','Country Code','Indicator Name','Indicator Code','1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'])

In [25]:
gdf_merged.columns

Index(['featurecla', 'scalerank', 'labelrank', 'sovereignt', 'sov_a3',
       'adm0_dif', 'level', 'type', 'tlc', 'admin',
       ...
       'fclass_bd', 'fclass_ua', 'filename', 'geometry', 'Country Name',
       'population_2018', 'population_2019', 'population_2020',
       'population_2021', 'population_2022'],
      dtype='object', length=176)

In [26]:
gdf_merged

,featurecla,scalerank,labelrank,sovereignt,sov_a3,adm0_dif,level,type,tlc,admin,...,fclass_bd,fclass_ua,filename,geometry,Country Name,population_2018,population_2019,population_2020,population_2021,population_2022
0,Admin-0 country,0,5,Costa Rica,CRI,0,2,Sovereign country,1,Costa Rica,...,None,None,CRI.geojson,"MULTIPOLYGON (((-83.69650 10.93659, -83.68687 ...",Costa Rica,5040734.0,5084532.0,5123105.0,5153957.0,5180829.0
1,Admin-0 country,0,5,Nicaragua,NIC,0,2,Sovereign country,1,Nicaragua,...,None,None,NIC.geojson,"MULTIPOLYGON (((-85.70174 11.08088, -85.70242 ...",Nicaragua,6572233.0,6663924.0,6755895.0,6850540.0,6948392.0
2,Admin-0 country,3,6,France,FR1,1,2,Dependency,1,Saint Martin,...,None,None,MAF.geojson,"POLYGON ((-63.01757 18.03339, -63.08589 18.058...",Saint Martin,33852.0,33121.0,32553.0,31948.0,31791.0
3,Admin-0 country,3,6,Netherlands,NL1,1,2,Country,1,Sint Maarten,...,None,None,SXM.geojson,"POLYGON ((-63.10700 18.06212, -63.08589 18.058...",Sint Maarten,40895.0,41608.0,42310.0,42668.0,42848.0
4,Admin-0 country,0,5,Haiti,HTI,0,2,Sovereign country,1,Haiti,...,None,None,HTI.geojson,"MULTIPOLYGON (((-71.75744 19.71011, -71.74861 ...",Haiti,11012421.0,11160438.0,11306801.0,11447569.0,11584996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Admin-0 country,3,5,Mauritius,MUS,0,2,Sovereign country,1,Mauritius,...,None,None,MUS.geojson,"MULTIPOLYGON (((57.79575 -20.22275, 57.79396 -...",Mauritius,1265577.0,1265985.0,1266014.0,1266334.0,1262523.0
254,Admin-0 country,5,5,United Kingdom,GB1,1,2,Disputed,1,British Indian Ocean Territory,...,None,None,IOT.geojson,"MULTIPOLYGON (((72.46754 -7.38388, 72.47153 -7...",NaN,NaN,NaN,NaN,NaN,NaN
255,Admin-0 country,5,5,Maldives,MDV,0,2,Sovereign country,1,Maldives,...,None,None,MDV.geojson,"MULTIPOLYGON (((73.16310 -0.68182, 73.17254 -0...",Maldives,489758.0,504508.0,514438.0,521457.0,523787.0
256,Admin-0 country,3,4,United Kingdom,GB1,1,2,Dependency,1,South Georgia and the Islands,...,None,None,SGS.geojson,"MULTIPOLYGON (((-27.25292 -59.45827, -27.24999...",NaN,NaN,NaN,NaN,NaN,NaN
257,Admin-0 country,6,5,France,FR1,1,2,Dependency,1,Clipperton Island,...,None,None,clippertoni.geojson,"POLYGON ((-109.21203 10.30268, -109.21036 10.2...",NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
gdf_merged.to_file('updated_map.geo.json', driver='GeoJSON')